// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bank.proto

package oaas

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBalanceResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Balance              *BalanceMessage `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{0}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetBalanceResponse) GetBalance() *BalanceMessage {
	if m != nil {
		return m.Balance
	}
	return nil
}

type UpdateBalanceRequest struct {
	Delta                int32    `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalanceRequest) Reset()         { *m = UpdateBalanceRequest{} }
func (m *UpdateBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceRequest) ProtoMessage()    {}
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{1}
}

func (m *UpdateBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceRequest.Unmarshal(m, b)
}
func (m *UpdateBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceRequest.Merge(m, src)
}
func (m *UpdateBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceRequest.Size(m)
}
func (m *UpdateBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceRequest proto.InternalMessageInfo

func (m *UpdateBalanceRequest) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type UpdateBalanceResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Balance              *BalanceMessage `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateBalanceResponse) Reset()         { *m = UpdateBalanceResponse{} }
func (m *UpdateBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceResponse) ProtoMessage()    {}
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{2}
}

func (m *UpdateBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceResponse.Unmarshal(m, b)
}
func (m *UpdateBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceResponse.Merge(m, src)
}
func (m *UpdateBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceResponse.Size(m)
}
func (m *UpdateBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceResponse proto.InternalMessageInfo

func (m *UpdateBalanceResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateBalanceResponse) GetBalance() *BalanceMessage {
	if m != nil {
		return m.Balance
	}
	return nil
}

type BalanceMessage struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceMessage) Reset()         { *m = BalanceMessage{} }
func (m *BalanceMessage) String() string { return proto.CompactTextString(m) }
func (*BalanceMessage) ProtoMessage()    {}
func (*BalanceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{3}
}

func (m *BalanceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceMessage.Unmarshal(m, b)
}
func (m *BalanceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceMessage.Marshal(b, m, deterministic)
}
func (m *BalanceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceMessage.Merge(m, src)
}
func (m *BalanceMessage) XXX_Size() int {
	return xxx_messageInfo_BalanceMessage.Size(m)
}
func (m *BalanceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceMessage proto.InternalMessageInfo

func (m *BalanceMessage) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBalanceResponse)(nil), "oaas.GetBalanceResponse")
	proto.RegisterType((*UpdateBalanceRequest)(nil), "oaas.UpdateBalanceRequest")
	proto.RegisterType((*UpdateBalanceResponse)(nil), "oaas.UpdateBalanceResponse")
	proto.RegisterType((*BalanceMessage)(nil), "oaas.BalanceMessage")
}

func init() { proto.RegisterFile("bank.proto", fileDescriptor_a6371916d5cb63b4) }

var fileDescriptor_a6371916d5cb63b4 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xb1, 0x4e, 0xf3, 0x40,
	0x0c, 0xc7, 0x95, 0x4f, 0x6d, 0x3e, 0xc9, 0x14, 0x06, 0x2b, 0x54, 0xd1, 0x75, 0x41, 0x11, 0x43,
	0x07, 0x74, 0x95, 0xca, 0xce, 0x50, 0x09, 0xc1, 0xc2, 0x12, 0xc4, 0x03, 0x38, 0xd4, 0x44, 0xa2,
	0xc9, 0x5d, 0xe0, 0x9c, 0x81, 0xb7, 0xe0, 0x91, 0x51, 0xcf, 0x29, 0xa8, 0x28, 0x2b, 0xa3, 0xed,
	0xdf, 0xf9, 0xef, 0xfb, 0x01, 0x54, 0xe4, 0x76, 0xb6, 0x7b, 0xf7, 0xe2, 0x71, 0xe2, 0x89, 0x82,
	0x59, 0xd4, 0xde, 0xd7, 0x0d, 0xaf, 0x62, 0xaf, 0xea, 0x5f, 0x56, 0xdc, 0x76, 0xf2, 0xa1, 0x88,
	0x99, 0x05, 0x21, 0xe9, 0x83, 0x56, 0xc5, 0x2b, 0xe0, 0x1d, 0xcb, 0x86, 0x1a, 0x72, 0xcf, 0x5c,
	0x72, 0xe8, 0xbc, 0x0b, 0x8c, 0x97, 0x90, 0x2a, 0x95, 0x27, 0x17, 0xc9, 0xf2, 0x64, 0x3d, 0xb3,
	0xfb, 0xbd, 0xf6, 0x31, 0xf6, 0xca, 0x61, 0x86, 0x16, 0xfe, 0x57, 0xfa, 0x30, 0xff, 0x17, 0xb1,
	0x4c, 0xb1, 0x61, 0xdb, 0x03, 0x87, 0x40, 0x35, 0x97, 0x07, 0xa8, 0xb8, 0x82, 0xec, 0xa9, 0xdb,
	0x92, 0xf0, 0x77, 0xdc, 0x5b, 0xcf, 0x41, 0x30, 0x83, 0xe9, 0x96, 0x1b, 0xa1, 0x18, 0x36, 0x2d,
	0xb5, 0x28, 0x5a, 0x38, 0xff, 0x45, 0xff, 0xe9, 0x71, 0x4b, 0x38, 0x3b, 0x1e, 0xe1, 0x1c, 0x52,
	0x6a, 0x7d, 0xef, 0x64, 0xb8, 0x6b, 0xa8, 0xd6, 0x9f, 0x09, 0x4c, 0x36, 0xe4, 0x76, 0x78, 0x03,
	0xf0, 0xe3, 0x0e, 0xe7, 0x56, 0xad, 0xdb, 0x83, 0x75, 0x7b, 0xbb, 0xb7, 0x6e, 0x72, 0xcd, 0x1d,
	0xb1, 0x7c, 0x0f, 0xa7, 0x47, 0x3f, 0x44, 0xa3, 0xe8, 0x98, 0x24, 0xb3, 0x18, 0x9d, 0xe9, 0xa6,
	0x2a, 0x8d, 0x99, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x19, 0x51, 0x65, 0x0b, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BankClient is the client API for Bank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BankClient interface {
	GetBalance(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error)
}

type bankClient struct {
	cc *grpc.ClientConn
}

func NewBankClient(cc *grpc.ClientConn) BankClient {
	return &bankClient{cc}
}

func (c *bankClient) GetBalance(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/oaas.Bank/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error) {
	out := new(UpdateBalanceResponse)
	err := c.cc.Invoke(ctx, "/oaas.Bank/UpdateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServer is the server API for Bank service.
type BankServer interface {
	GetBalance(context.Context, *empty.Empty) (*GetBalanceResponse, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error)
}

// UnimplementedBankServer can be embedded to have forward compatible implementations.
type UnimplementedBankServer struct {
}

func (*UnimplementedBankServer) GetBalance(ctx context.Context, req *empty.Empty) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedBankServer) UpdateBalance(ctx context.Context, req *UpdateBalanceRequest) (*UpdateBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBalance not implemented")
}

func RegisterBankServer(s *grpc.Server, srv BankServer) {
	s.RegisterService(&_Bank_serviceDesc, srv)
}

func _Bank_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oaas.Bank/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).GetBalance(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oaas.Bank/UpdateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bank_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oaas.Bank",
	HandlerType: (*BankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Bank_GetBalance_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _Bank_UpdateBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
