// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omikuji.proto

package oaas

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrawOmikujiRequest struct {
	Seed                 int32                `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DrawOmikujiRequest) Reset()         { *m = DrawOmikujiRequest{} }
func (m *DrawOmikujiRequest) String() string { return proto.CompactTextString(m) }
func (*DrawOmikujiRequest) ProtoMessage()    {}
func (*DrawOmikujiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c523fe4d67b8cba0, []int{0}
}

func (m *DrawOmikujiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawOmikujiRequest.Unmarshal(m, b)
}
func (m *DrawOmikujiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawOmikujiRequest.Marshal(b, m, deterministic)
}
func (m *DrawOmikujiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawOmikujiRequest.Merge(m, src)
}
func (m *DrawOmikujiRequest) XXX_Size() int {
	return xxx_messageInfo_DrawOmikujiRequest.Size(m)
}
func (m *DrawOmikujiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawOmikujiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawOmikujiRequest proto.InternalMessageInfo

func (m *DrawOmikujiRequest) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *DrawOmikujiRequest) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type DrawOmikujiResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Omikuji              *OmikujiMessage `protobuf:"bytes,2,opt,name=omikuji,proto3" json:"omikuji,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DrawOmikujiResponse) Reset()         { *m = DrawOmikujiResponse{} }
func (m *DrawOmikujiResponse) String() string { return proto.CompactTextString(m) }
func (*DrawOmikujiResponse) ProtoMessage()    {}
func (*DrawOmikujiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c523fe4d67b8cba0, []int{1}
}

func (m *DrawOmikujiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawOmikujiResponse.Unmarshal(m, b)
}
func (m *DrawOmikujiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawOmikujiResponse.Marshal(b, m, deterministic)
}
func (m *DrawOmikujiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawOmikujiResponse.Merge(m, src)
}
func (m *DrawOmikujiResponse) XXX_Size() int {
	return xxx_messageInfo_DrawOmikujiResponse.Size(m)
}
func (m *DrawOmikujiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawOmikujiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrawOmikujiResponse proto.InternalMessageInfo

func (m *DrawOmikujiResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DrawOmikujiResponse) GetOmikuji() *OmikujiMessage {
	if m != nil {
		return m.Omikuji
	}
	return nil
}

type OmikujiMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OmikujiMessage) Reset()         { *m = OmikujiMessage{} }
func (m *OmikujiMessage) String() string { return proto.CompactTextString(m) }
func (*OmikujiMessage) ProtoMessage()    {}
func (*OmikujiMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c523fe4d67b8cba0, []int{2}
}

func (m *OmikujiMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OmikujiMessage.Unmarshal(m, b)
}
func (m *OmikujiMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OmikujiMessage.Marshal(b, m, deterministic)
}
func (m *OmikujiMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OmikujiMessage.Merge(m, src)
}
func (m *OmikujiMessage) XXX_Size() int {
	return xxx_messageInfo_OmikujiMessage.Size(m)
}
func (m *OmikujiMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OmikujiMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OmikujiMessage proto.InternalMessageInfo

func (m *OmikujiMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DrawOmikujiRequest)(nil), "oaas.DrawOmikujiRequest")
	proto.RegisterType((*DrawOmikujiResponse)(nil), "oaas.DrawOmikujiResponse")
	proto.RegisterType((*OmikujiMessage)(nil), "oaas.OmikujiMessage")
}

func init() { proto.RegisterFile("omikuji.proto", fileDescriptor_c523fe4d67b8cba0) }

var fileDescriptor_c523fe4d67b8cba0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xe8, 0x1f, 0x9c, 0x54, 0x0f, 0x63, 0x0f, 0x71, 0x2f, 0x96, 0x20, 0x52, 0x3c,
	0x6c, 0x21, 0x7e, 0x03, 0xf1, 0x5a, 0x84, 0xb5, 0x5f, 0x60, 0x8b, 0x63, 0x88, 0x6d, 0xdc, 0xd8,
	0xd9, 0xd5, 0xaf, 0x2f, 0xee, 0x6c, 0xc0, 0xa0, 0xb7, 0x9d, 0x79, 0x8f, 0xf7, 0x9b, 0xb7, 0x70,
	0xee, 0xba, 0xf6, 0x10, 0xde, 0x5a, 0xdd, 0x9f, 0x9c, 0x77, 0x38, 0x71, 0xd6, 0xb2, 0xba, 0x6e,
	0x9c, 0x6b, 0x8e, 0xb4, 0x89, 0xbb, 0x7d, 0x78, 0xdd, 0xf8, 0xb6, 0x23, 0xf6, 0xb6, 0xeb, 0xc5,
	0xa6, 0x16, 0xec, 0xad, 0x0f, 0x2c, 0x53, 0xb5, 0x03, 0x7c, 0x3c, 0xd9, 0xaf, 0x27, 0x49, 0x32,
	0xf4, 0x11, 0x88, 0x3d, 0x22, 0x4c, 0x98, 0xe8, 0xa5, 0xcc, 0x56, 0xd9, 0x7a, 0x6a, 0xe2, 0x1b,
	0xef, 0x20, 0xf7, 0x5c, 0xe6, 0xab, 0x6c, 0x5d, 0xd4, 0x4a, 0x0b, 0x45, 0x0f, 0x14, 0xbd, 0x1b,
	0x28, 0x26, 0xf7, 0x5c, 0x1d, 0xe0, 0x72, 0x94, 0xca, 0xbd, 0x7b, 0x67, 0xc2, 0x1b, 0x98, 0x09,
	0x3c, 0x06, 0x17, 0xf5, 0x42, 0xff, 0x9c, 0xac, 0x9f, 0xe3, 0xce, 0x24, 0x0d, 0x35, 0xcc, 0x53,
	0xb1, 0x44, 0x5b, 0x8a, 0x2d, 0xa5, 0x6d, 0x89, 0xd9, 0x36, 0x64, 0x06, 0x53, 0x75, 0x0b, 0x17,
	0x63, 0x09, 0x97, 0x30, 0xfd, 0xb4, 0xc7, 0x40, 0x11, 0x73, 0x66, 0x64, 0xa8, 0xb7, 0x30, 0x4f,
	0x3e, 0x7c, 0x80, 0xe2, 0xd7, 0x7d, 0x58, 0x0a, 0xe0, 0xef, 0x47, 0xa8, 0xab, 0x7f, 0x14, 0x29,
	0xb3, 0x9f, 0xc5, 0xee, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86, 0x29, 0x18, 0x77, 0x86,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OmikujiClient is the client API for Omikuji service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OmikujiClient interface {
	DrawOmikuji(ctx context.Context, in *DrawOmikujiRequest, opts ...grpc.CallOption) (*DrawOmikujiResponse, error)
}

type omikujiClient struct {
	cc *grpc.ClientConn
}

func NewOmikujiClient(cc *grpc.ClientConn) OmikujiClient {
	return &omikujiClient{cc}
}

func (c *omikujiClient) DrawOmikuji(ctx context.Context, in *DrawOmikujiRequest, opts ...grpc.CallOption) (*DrawOmikujiResponse, error) {
	out := new(DrawOmikujiResponse)
	err := c.cc.Invoke(ctx, "/oaas.Omikuji/DrawOmikuji", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmikujiServer is the server API for Omikuji service.
type OmikujiServer interface {
	DrawOmikuji(context.Context, *DrawOmikujiRequest) (*DrawOmikujiResponse, error)
}

// UnimplementedOmikujiServer can be embedded to have forward compatible implementations.
type UnimplementedOmikujiServer struct {
}

func (*UnimplementedOmikujiServer) DrawOmikuji(ctx context.Context, req *DrawOmikujiRequest) (*DrawOmikujiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrawOmikuji not implemented")
}

func RegisterOmikujiServer(s *grpc.Server, srv OmikujiServer) {
	s.RegisterService(&_Omikuji_serviceDesc, srv)
}

func _Omikuji_DrawOmikuji_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawOmikujiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmikujiServer).DrawOmikuji(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oaas.Omikuji/DrawOmikuji",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmikujiServer).DrawOmikuji(ctx, req.(*DrawOmikujiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Omikuji_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oaas.Omikuji",
	HandlerType: (*OmikujiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DrawOmikuji",
			Handler:    _Omikuji_DrawOmikuji_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "omikuji.proto",
}
